## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [1]:
import numpy as np
array = np.arange(50,101)
array

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [2]:
array_1 = np.ones((3,3))
array_2 = np.pad(array_1,pad_width =1)
print("original array",array_1)
print("second array",array_2)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [6]:
lst = [1,2,3,4,5,6,7,8]
s=np.array(lst)
print(s)
print(type(s))

tup=(8,4,6,1,2,3)
arr =np.array(tup).reshape(2,3)
print(arr)

s_array = np.asarray(tup)
s_array

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [4]:
faren_array = np.array([0.  , 12.  , 45.21, 34. ,  99.91])
centi_lst=[]
for i in faren_array:
    temp_lst =(i-32)/1.8
    centi_lst.append(temp_lst)
centi_array = np.asarray(centi_lst)
print("Fahrenheit",faren_array)
print("Centigrade",centi_array)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [7]:
array_1= np.array([1,3,5], dtype=np.float64)
print("size of array",len(array_1))
print("size of array",array_1.size)
print("Length of one array element in bytes:",array_1.itemsize)
print("Total bytes consumed by the elements of the array:",array_1.nbytes)

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


## Exercise 6: Get the unique elements of an array

In [9]:
array_1 = np.array([10,10,20,4,9,9,5])
x=np.unique(array_1)
x
array_2 = np.array([[2,2,3],[4,6,6]])
array_3 = array_2.reshape(2,3)
print(array_3)
y=np.unique(array_3)
y

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


## Exercise 7: Change the dimension of an array


In [11]:
array_1 =np.array([1, 2 ,3 ,4 ,5 ,6, 7 ,8, 9])
array_2= array_1.reshape(3,3)
print("Original array:",array_1)
print("reshaped array\n",array_2)

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [12]:
array_1 =np.linspace(2.5,6.5,30)
print(array_1)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [21]:
array_1 =np.array([10,20,30])
array_2 =np.array([40,50,60])
res_array= np.stack((array_1,array_2),axis=1)
print(res_array)

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [22]:
array_1 =np.zeros((5,5))
print(array_1)
array_2 =np.arange(5)
array_2= array_1+array_2
print(array_2)

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [23]:
array_1 = np.arange(1, 100)
n= array_1[(array_1 % 3 == 0) | (array_1 % 5 == 0)]
print(n[:100])
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [29]:
array_1 = np.array([0,1,2,3])
array_2 = np.arange(8).reshape(2,4)
print("One dimensional array:")
print(array_1)
print("two dimensional array:")
print(array_2)
for x,y in np.nditer([array_1,array_2]):
    print("%d:%d" % (x,y),)


One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [30]:
array_1 = np.array([0.42436315 ,0.48558583 ,0.32924763,0.7439979 , 0.58220701, 0.38213418,0.5097581,  0.34528799 ,0.1563123])
array_1 = array_1.reshape(3,3)
print("Original array")
print(array_1)
print("Replace all elements of the said array with .5 which are greater than .5")
array_1[array_1>.5] = .5
print(array_1)

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [34]:
array_1 =np.empty((0,3), int)
print("empty array")
print(array_1)
array_1 =np.append(array_1,np.array([[10 ,20 ,30]]),axis=0)
array_1 = np.append(array_1,np.array([[40 ,50 ,60]]),axis=0)
print("After adding two new arrays:")
print(array_1)

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [35]:
array_1 = np.array([1,2,3])
array_2 = np.array([2,3,4])
print("Original Arrays:")
print(array_1)
print(array_2)
print("Sequence of arrays along a new axis:")
array_3 = np.stack((array_1,array_2))
print(array_3)
arr_1 =np.array([1,2,3])
arr_2 =np.array([2,3,4])
print("Original arrays")
array_4 = arr_1.transpose()
array_5 = arr_2.transpose()
print(array_4)
print(array_5)
print("sequence of arrays along a new axis:\n" ,np.stack((array_4,array_5)).reshape(6,1))


Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
